# Generated by Django 5.0.6 on 2025-08-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='complaints/')),
                ('predicted_severity', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('severe', 'Severe')], max_length=16)),
                ('confidence', models.FloatField(default=0.0)),
                ('generated_text', models.TextField(blank=True)),
                ('mongo_file_id', models.CharField(blank=True, default='', max_length=64)),
            ],
        ),
    ]
