# Generated by Django 5.0.6 on 2025-09-14 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_complaint_true_severity_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='predicted_severity',
            field=models.CharField(choices=[('good', 'Good'), ('minor', 'Minor'), ('moderate', 'Moderate'), ('severe', 'Severe')], max_length=16),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='true_severity',
            field=models.CharField(blank=True, choices=[('good', 'Good'), ('minor', 'Minor'), ('moderate', 'Moderate'), ('severe', 'Severe')], default='', max_length=16),
        ),
        migrations.CreateModel(
            name='AadhaarOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhaar_hash', models.CharField(max_length=128)),
                ('otp_hash', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.IntegerField(default=0)),
                ('verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aadhaar_otps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
