# Generated by Django 5.2.6 on 2025-09-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_alter_complaint_predicted_severity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='location',
            field=models.CharField(blank=True, help_text='Location where the pothole was found', max_length=200),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='predicted_severity',
            field=models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('severe', 'Severe')], max_length=16),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='true_severity',
            field=models.CharField(blank=True, choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('severe', 'Severe')], default='', max_length=16),
        ),
    ]
