# Generated by Django 5.2.8 on 2025-11-19 06:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_comment_is_official_comment_announcement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='complaints_upvoted', to=settings.AUTH_USER_MODEL),
        ),
    ]
